I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/train.rpy", line 673, in script
    bp "Epicchamp!"
Exception: Sayer 'bp' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/train.rpy", line 673, in script
    bp "Epicchamp!"
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'bp' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
tead .1
Tue Mar  9 18:03:10 2021
